### ISSUE TITLE
Stable version of `memo()`.

### ISSUE THREAD

**Issue by izakfilmalter** [mblink/fp-ts-react-stable-hooks#5]
I know this is probably a bit out of scope for this lib. Would be nice to have a stable version of `memo()`.

**Comment by vvzz** [comment]
I believe React.memo actually supports a custom equality checker right out of the box. So you can just shove an Eq instance there

React.memo(Component, [areEqual(prevProps, nextProps)]);

**Comment by jleider** [comment]
@vvzz is correct, you can see the argument here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L834
